version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgres://ivan:Lilcheeks200w@localhost:5432/postgres?application_name=postgres
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=Lilcheeks200w
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
